### ISSUE TITLE
Final Group Capstone Project

### ISSUE THREAD

**Issue by DyaryRaoof** [DyaryRaoof/motors-backend#10]
https://github.com/DyaryRaoof/motors-backend
There are 3 people in this team. @mustabbas , @DyaryRaoof and @peterdgreat 
<img width="2560" alt="Screen Shot 2022-02-23 at 6 22 22 PM" src="https://user-images.githubusercontent.com/40565209/155349728-cee9390b-f5f0-45ff-a617-14c4e15e5cf0.png">

**Comment by MuriloRoque** [comment]
Hi @DyaryRaoof, @mustabbas, @peterdgreat,

In my opinion, your project is complete!

Good luck! 🎉 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
